apiVersion: apps/v1
kind: Deployment
metadata:
  name: crud-backend
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: crud-backend
  template:
    metadata:
      labels:
        app: crud-backend
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - worker1
                      - worker2
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - crud-backend
              topologyKey: kubernetes.io/hostname
      containers:
        - name: crud-backend
          image: nina323/crudback
          ports:
            - containerPort: 80
          env:
            - name: DB_HOST
              value: "db.default.svc.cluster.local"
            - name: DB_USER
              value: "root"
            - name: DB_PASS
              value: "secret"
            - name: DB_NAME
              value: "db2"
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: crud-backend-svc
  namespace: default
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.0.200
spec:
  selector:
    app: crud-backend
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 80
